- hosts: awsHTTPserver #To manage the target node you can change this line with ip files directory.
  become: true #  privilege escalation systems to execute tasks with root privileges or with another user's permissions
  tasks:

  - name: "installing http packges"
    package: 
         name: "httpd"
         state: present

  - name: "installing php"
    package: 
         name: "php"
         state: present

  - name: "coping file"
    copy:
        src: "index.php"
        dest: "/var/www/html/"

  - service: 
         name: "httpd"
         state: started
         enabled: yes
         
# add follwing line of code while configuring the haproxy on local system vm's
#  - firewalld:
#        port: "80/tcp"
#        state: enabled
#        permanent: yes
#        immediate: yes
 

  

- hosts: awsHAproxy #you can change this 127.0.0.1 when you wanted to confgure load balancer over controller node
  become: true
  tasks:

  - package:
       name: "haproxy"
       state: present 
 
  - template:
         src: haproxy.cfg.j2
         dest: "/etc/haproxy/haproxy.cfg"
    register: status

  - service:
         name: "haproxy"
         state: restarted
    when: status.changed == true


